package mascotaAPP;


/**
* mascotaAPP/MascotaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mascota.idl
* lunes 14 de mayo de 2018 06:17:51 PM COT
*/

public interface MascotaOperations 
{
  boolean insertarMascota (int id, String nombreMascota, String apellidoMascota, String nombreDueno, int telefonoDueno);
  String consultarMascota (int id);
  boolean eliminarMascota (int id);
  boolean actualizarMascota (int id, String nombreMascota, String apellidoMascota, String nombreDueno, int telefonoDueno);
  String listarMascota ();
  void shutdown ();
} // interface MascotaOperations
