package mascotaAPP;

/**
* mascotaAPP/MascotaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mascota.idl
* lunes 14 de mayo de 2018 06:17:51 PM COT
*/

public final class MascotaHolder implements org.omg.CORBA.portable.Streamable
{
  public mascotaAPP.Mascota value = null;

  public MascotaHolder ()
  {
  }

  public MascotaHolder (mascotaAPP.Mascota initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = mascotaAPP.MascotaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    mascotaAPP.MascotaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return mascotaAPP.MascotaHelper.type ();
  }

}
