package mascotaAPP;


/**
* mascotaAPP/MascotaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mascota.idl
* lunes 14 de mayo de 2018 06:17:51 PM COT
*/

abstract public class MascotaHelper
{
  private static String  _id = "IDL:mascotaAPP/Mascota:1.0";

  public static void insert (org.omg.CORBA.Any a, mascotaAPP.Mascota that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static mascotaAPP.Mascota extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (mascotaAPP.MascotaHelper.id (), "Mascota");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static mascotaAPP.Mascota read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MascotaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, mascotaAPP.Mascota value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static mascotaAPP.Mascota narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof mascotaAPP.Mascota)
      return (mascotaAPP.Mascota)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      mascotaAPP._MascotaStub stub = new mascotaAPP._MascotaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static mascotaAPP.Mascota unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof mascotaAPP.Mascota)
      return (mascotaAPP.Mascota)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      mascotaAPP._MascotaStub stub = new mascotaAPP._MascotaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
