package mascotaAPP;


/**
* mascotaAPP/Mascota.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from mascota.idl
* lunes 14 de mayo de 2018 06:17:51 PM COT
*/

public interface Mascota extends MascotaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Mascota
